# This file was generated by GoReleaser. DO NOT EDIT.
cask "task-compose" do
  desc "Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
  homepage "https://github.com/vulcanshen-tpi/task-compose"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "task-compose"

  on_macos do
    on_intel do
      url "https://github.com/vulcanshen-tpi/task-compose/releases/download/v1.1.1/task-compose_1.1.1_darwin_amd64.tar.gz"
      sha256 "20da5634ea6ab4e67236807181d1af31dc25cc579409e7d9284a1872f9243f5d"
    end
    on_arm do
      url "https://github.com/vulcanshen-tpi/task-compose/releases/download/v1.1.1/task-compose_1.1.1_darwin_arm64.tar.gz"
      sha256 "fa0dc1fea33938cff6eec9159897e55a20eca4cb2c9d4fedaefa4e5e3be1d3e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vulcanshen-tpi/task-compose/releases/download/v1.1.1/task-compose_1.1.1_linux_amd64.tar.gz"
      sha256 "5671ea55de76a08ffb642082f15e1d990b8db888d8bcbee019c2542ca53a3afa"
    end
    on_arm do
      url "https://github.com/vulcanshen-tpi/task-compose/releases/download/v1.1.1/task-compose_1.1.1_linux_arm64.tar.gz"
      sha256 "3457551a47aeedbc0b63e9f4eb4264993e5070e7f401f75bf63c0d67e9e80b7c"
    end
  end

  # No zap stanza required
end
