# This file was generated by GoReleaser. DO NOT EDIT.
cask "task-compose" do
  desc "Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
  homepage "https://github.com/vulcanshen-tpi/task-compose"
  version "1.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "task-compose"

  on_macos do
    on_intel do
      url "https://github.com/vulcanshen-tpi/task-compose/releases/download/v1.1.2/task-compose_1.1.2_darwin_amd64.tar.gz"
      sha256 "dd6e68cd845e751fd495d746e2c248f460f5534e1e8e2b6168a4810b2e809136"
    end
    on_arm do
      url "https://github.com/vulcanshen-tpi/task-compose/releases/download/v1.1.2/task-compose_1.1.2_darwin_arm64.tar.gz"
      sha256 "c3533941c60b4376c762603ad68112ae2d4cd75115ac3367440035e6e59ec9a1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vulcanshen-tpi/task-compose/releases/download/v1.1.2/task-compose_1.1.2_linux_amd64.tar.gz"
      sha256 "a615a3744e595ab75f273970dcf16bc80d4915035da56b576e150cfb0bf81d26"
    end
    on_arm do
      url "https://github.com/vulcanshen-tpi/task-compose/releases/download/v1.1.2/task-compose_1.1.2_linux_arm64.tar.gz"
      sha256 "5a1016d4eadf0704e05f0dbc3e264577fa326b56967765a8e3653d21fff8253e"
    end
  end

  # No zap stanza required
end
